### ISSUE TITLE
Change DaoConstants to DaoAdapterConstants?

### ISSUE THREAD

**Issue by jtrein** [openlawteam/molochv3-ui#183]
- [x] It would be good to update the definition name and usages of `DaoConstants`. Whichever name chosen is fine. This is to differentiate adapter names from other DAO constants, like addresses.
- [x] It would also be good to remove `OFFCHAINVOTING`, as it's not in `DaoConstant.sol` in Tribute, and include the new name where needed. `OFFCHAINVOTING` is used in 3 places; where needed, the type could be updated to something like `DaoAdapterConstants | OtherAdapterConstants.OFFCHAINVOTING` to not break TS lint.

**Comment by sophiacodes** [comment]
https://github.com/openlawteam/molochv3-ui/pull/new/issue-183
