### ISSUE TITLE
Redux state when subgraph is up/down

### ISSUE THREAD

**Issue by jtrein** [openlawteam/molochv3-ui#190]
Across the app, we need a way to know when to fall back to on-chain fetching of data. A way to solve this is by detecting when the subgraph goes down and setting the state.

**Things to solve**

- [ ] How do we know when the subgraph stops working (i.e. a query running through the Apollo provider fails). Is there a way in the Apollo provider to know this? After we can do this, it's just a matter of setting up/down states.

**Comment by sophiacodes** [comment]
FYI https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health

**Comment by jtrein** [comment]
(Also posted in Slack chat with Sophia, Jarrel, Jeremiah)

I may have a solution that sits closer to `ApolloClient`. Let me write some pseudo code. It should be able to accommodate multiple error types.

We may also be able to decide which types of apollo errors we want to handle. Link to error types: https://www.apollographql.com/docs/react/data/error-handling/

example code:

```
import { onError } from "@apollo/client/link/error";
const httpLink = new HttpLink({ uri: '/graphql' });
// Log any GraphQL errors or network error that occurred
const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    store.dispatch({type: SET_SUBGRAPH_STATUS, OK: false})
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );
  if (networkError) {
    store.dispatch({type: SET_SUBGRAPH_STATUS, OK: false})
    console.log(`[Network error]: ${networkError}`);
  }
});
const getClient = (store) => {
  return new ApolloClient({
    cache: new InMemoryCache(),
    link: concat(errorLink, httpLink),
  });
}
<ApolloProvider client={getClient(store)}>
  ...
</ApolloProvider>
```

Ref: https://www.apollographql.com/docs/react/api/link/apollo-link-error/

If we wanted to check when it was back up, we'd also need a hook running higher in the app (I assume) to poll a gql query (like @Jarrel is using) when the `OK === false`. Then inside the `errorLink` handler we could manage to set the state to true (being previously false on the account of an error) once there's no errors.
