### ISSUE TITLE
Update Rinkeby demo voting period(s)

### ISSUE THREAD

**Issue by jtrein** [openlawteam/molochv3-ui#204]
Related to #202 

Feedback from David while demo-ing https://molochv3.org:

> Could we change the voting period (and also grace period) to 10 min instead of 1 ? It is very short and when you demo it looks like it does not work.

**Off-chain**

- [ ] Voting period: 10min
- [ ] Grace period: 10min

**On-chain**

- [ ] Voting period: 10min
- [ ] Grace period: 10min

**Comment by jdville03** [comment]
Closing this issue here since we'll manage this update in openlawteam/molochv3-contracts#214.
