### ISSUE TITLE
Proposal with passing vote and results not yet submitted is categorized as "Failed".

### ISSUE THREAD

**Issue by jdville03** [openlawteam/molochv3-ui#227]
Steps to reproduce:
1. Submit a proposal (e.g., membership).
2. Sponsor the proposal.
3. Vote "Yes" to pass the proposal.
4. After the voting period has ended and **before the results are submitted** - view all the proposals to see that it is categorized under "Failed".

**Comment by jtrein** [comment]
Thanks for noticing this. I will look into this.

**Comment by jtrein** [comment]
Reproduced:

<img width="367" alt="Screen Shot 2021-04-08 at 11 47 35" src="https://user-images.githubusercontent.com/1144320/114014209-43666b00-9860-11eb-8247-e28cff623a09.png">
<img width="366" alt="Screen Shot 2021-04-08 at 11 47 42" src="https://user-images.githubusercontent.com/1144320/114014217-44979800-9860-11eb-9921-dbed74b5537f.png">

**Comment by jtrein** [comment]
The best and actually easiest way to fix this is to place it in the "Voting" category. The reasons are:

- There are no votes data submitted to the contract for the off-chain vote, yet. Technically, it has not passed.
- Grace period does not start until the votes results are submitted.

It could be good to try and include a new status when a vote result has not yet been submitted. Something to the effect of "Ready to submit result" could work. I can create a new issue for this.

**Comment by jdville03** [comment]
We were able to reproduce the bug still with this test proposal: https://molochv3.org/membership/0x20a3737e0a4da49bbf3e600035251fbe031291d2a8bd01af10154abb3973553e

The vote is passing and the vote results have not yet been submitted. (From the proposal details page, click "view all" to see it listed under "Failed".)

**Comment by jdville03** [comment]
Looks like this bug applies when there are "NO" votes. If there are only "YES" votes, then the proposal correctly is listed under the "Voting" category.

**Comment by jtrein** [comment]
Having trouble reproducing this one. I have tested locally with the latest contracts from PR #251 and I get the correct result.

I tested the following: 

- Only "yes" votes: OK
- Only "no" votes: OK
- More "yes" than "no" **to match upstream bug**: OK

<img width="351" alt="Screen Shot 2021-04-14 at 16 20 50" src="https://user-images.githubusercontent.com/1144320/114735870-7ff10580-9d3d-11eb-927d-505e9d53979e.png">

**Comment by jdville03** [comment]
Unfortunately this bug is reappearing again.

https://molochv3.org/membership

The two listed "Failed" proposals have passing votes and the vote result has not been submitted.

**Comment by jdville03** [comment]
A related bug has recently appeared:
1. Voting period has expired with more YES votes than NO votes.
2. Grace period has expired and vote result has not been submitted yet.
3. The proposal is listed under the "Failed" category (when it should be listed under "Voting").
