### ISSUE TITLE
Can't sponsor membership (ganache)

### ISSUE THREAD

**Issue by sophiacodes** [openlawteam/molochv3-ui#252]
The sponsor button is not rendering when a proposal for membership is submitted. This is happening locally, to reproduce checkout branch `contract-updates` and update the `config.ts` with your local ganache contracts, submit a join proposal via http://localhost:3000/join and click the prompts. 

I console logged the `status` var from the hook and it was `undefined` 

<img width="1219" alt="Screenshot 2021-04-14 at 09 55 53" src="https://user-images.githubusercontent.com/2333082/114685078-73eb5080-9d09-11eb-90bb-38e66b65bdd3.png">

**Comment by jtrein** [comment]
I was able to reproduce the issue. There is no error in the UI or developer console output.

**Comment by jtrein** [comment]
Oops, I was using the wrong combination of contract addresses. I was using a Multicall contract from Rinkeby for a local Ganche environment. The flow works for both @sophiacodes and I now.
