### ISSUE TITLE
[Question] Possible unnecessary ERC20 approve call when Tribute proposal fails

### ISSUE THREAD

**Issue by jtrein** [openlawteam/molochv3-ui#273]
In PR #272 it's mentioned about a Tribute proposal: _"If the proposal failed, anyone can process it."_.

If this is true, shouldn't we skip the `await handleSubmitTokenApprove()` as we only need the `processProposal` tx?

Perhaps changing it to: `isProposalPassed && await handleSubmitTokenApprove();` would be better?

**Note:** I have not tested this! I have only read the code.

**Comment by adridadou** [comment]
I actually would go further and just not let anyone process it if it has failed since it does not matter.

**Comment by jdville03** [comment]
Good catch @jtrein.

Yeah I agree there's no reason to process if it failed with the new contract. I'll update to skip that.
